### PR TITLE
Support multiple dfp versions using reflection

### PR DESCRIPTION
**Pull request by piumika**
Hi @tonivdv ,

I have included the joor library for reflection and generics. Please let me know if there is a better way for handling generics.

If an older dfp version does not support a certain method it will throw a RunTimeException specifying the class and the method. Let me know if there is any other better way for handling these scenarios.

Also I could not find a good way for validating the service objects that are passed to the finders (ex: InventoryServiceInterface in AdUnitFinder), since these objects are proxy objects. I have used the proxy objects invocation handler to find the soapclient specific to the service and validated using this.

Kind Regards
Piumika

### CODE REVIEW

**Comment by tonivdv** [comment]
@piumika Adding the joor library makes the reflection more readable, however I kind of agree with gunith about the DfpVersion. This how a dev now will interact with this library:

``` java
@Test
	public void test() {

		// Initialization of the Finder class if you cached the services
		InventoryServiceInterface inventoryService =
		    mock(InventoryServiceInterface.class);

		NetworkServiceInterface networkService =
		    mock(NetworkServiceInterface.class);

		AdUnitFinder<AdUnit> adUnitFinder = new AdUnitFinder<AdUnit>(inventoryService, networkService, DfpVersion.V_201403);
		
		// Find the Effective Root AdUnit
		AdUnit rootAdUnit = adUnitFinder.findRoot();

	}
```

What's very strange here, is that you have to pass the version in order to do some background stuff ... 

And here again I come back to my previous question, why can't we make constructors that accepts all the versions we support? Now it will accept any object, unless they know exactly what to set in the generics.

Anyway we need to think also about the easiness to use this library. Currently it's a bit odd ...

**Comment by piumika** [comment]
Hello @tonivdv ,

I agree with you that passing the dfpversion and the methods accepting any object is not so good. I had to do it this way as I could not find a better simpler solution. 
I tried to add constructors for all the versions we support but it became a bit cumbersome as multiple constructors had to be added in all the classes (finders, services and domains) and managing it was a bit difficult.

I will further see how I could use multiple constructors for all versions and make the objects strongly typed.  

Kind Regards
Piumika

**Comment by piumika** [comment]
Hello @tonivdv ,
I further checked whether there is any way to make the parameters strongly typed, but unfortunately I could not find any solution.
As you suggested I tried overloading the constructors with different versions. But all the constructors ,public methods in all the classes (finders, services and domains) have to be overloaded with each dfp version and this became very difficult to manage.The classes became huge and when there is a new version all the classes have to be changed.(I feel that it would be much more complex and difficult to manage than the current solution of copying classes)
I cannot think of a good solution for this problem.

@gunith , did you find any solution with the singleton factory?

Kind Regards
Piumika

**Comment by tonivdv** [comment]
@piumika yes correct that's indeed a side effect I didn't think off :(

**Comment by tonivdv** [comment]
@piumika we can finetune how it is currently done. I would just try to find something for that version injection each time

**Comment by piumika** [comment]
Ok @tonivdv , will try to come up with a solution to bypass the version injection.

cc @gunith

**Comment by piumika** [comment]
Hello @tonivdv 
I could think of two solutions for this problem.
**Solution 1**
``` java
public class DfpFinderFactory {
	private AdUnitFinder<?> adUnitFinder;	
	private OrderFinder<?> orderFinder;
	private DfpServices dfpServices;
	private DfpSession dfpSession;

	public DfpFinderFactory(DfpServices dfpServices, DfpSession dfpSession) {
		super();
		this.dfpServices = dfpServices;
		this.dfpSession = dfpSession;
	}

	public AdUnitFinder<AdUnit> getAdUnitFinderV201403() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession, DfpVersion.V_201403);
		}
		return (AdUnitFinder<AdUnit>) adUnitFinder;
	}

	public AdUnitFinder<com.google.api.ads.dfp.axis.v201405.AdUnit> getAdUnitFinderV201405() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession, DfpVersion.V_201405);
		}
		return (AdUnitFinder<com.google.api.ads.dfp.axis.v201405.AdUnit>) adUnitFinder;
	}

	public AdUnitFinder<com.google.api.ads.dfp.axis.v201408.AdUnit> getAdUnitFinderV201408() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession, DfpVersion.V_201408);
		}
		return (AdUnitFinder<com.google.api.ads.dfp.axis.v201408.AdUnit>) adUnitFinder;
	}
}
```
This will be invoked as
``` java
DfpFinderFactory dfpFinderFactory = new DfpFinderFactory(dfpServices, dfpSession);
		AdUnitFinder<com.google.api.ads.dfp.axis.v201408.AdUnit> adUnitFinder = dfpFinderFactory.getAdUnitFinderV201408();
		com.google.api.ads.dfp.axis.v201408.AdUnit adUnit = adUnitFinder.findRoot();
```

As given above the getAdUnitFinderV201408() will return a strongly typed object

**Solution 2**
``` java
public class DfpFinderFactory {

	private AdUnitFinder<?> adUnitFinder;
	private OrderFinder<?> orderFinder;
	private DfpServices dfpServices;
	private DfpSession dfpSession;
	private DfpVersion dfpVersion;

	public DfpFinderFactory(DfpVersion version, DfpServices dfpServices, DfpSession dfpSession) {
		super();
		this.dfpServices = dfpServices;
		this.dfpSession = dfpSession;
		this.dfpVersion = version;
	}
public <T> AdUnitFinder<T> getAdUnitFinder() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<T>(dfpServices, dfpSession, dfpVersion);
		}
		return (AdUnitFinder<T>) adUnitFinder;
	}
}
```
This will be invoked as
``` java
	DfpFinderFactory dfpFinderFactory = new DfpFinderFactory(DfpVersion.V_201403, dfpServices, dfpSession);
		AdUnitFinder<AdUnit> adUnitFinder=dfpFinderFactory.getAdUnitFinder();
		.AdUnit adUnit = adUnitFinder.findRoot();
```
As given above the getAdUnitFinder() will return a ``` AdUnitFinder<Object>``` and the user can set anything for the generic type <AdUnit>. But if a wrong type is set then a Runtime exception will be thrown.

Out of the above solutions I prefer Solution 1. Let me know your ideas on this. Will further see if there is a better way to solve this.

cc @gunith 

Piumika

**Comment by piumika** [comment]
Hello @tonivdv 
I could think of three solutions for this problem.
**Solution 1**
Have a single Finder Factory for all versions.
``` java
public class DfpFinderFactory {
	private AdUnitFinder<?> adUnitFinder;	
	private OrderFinder<?> orderFinder;
	private DfpServices dfpServices;
	private DfpSession dfpSession;

	public DfpFinderFactory(DfpServices dfpServices, DfpSession dfpSession) {
		super();
		this.dfpServices = dfpServices;
		this.dfpSession = dfpSession;
	}

	public AdUnitFinder<AdUnit> getAdUnitFinderV201403() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession, DfpVersion.V_201403);
		}
		return (AdUnitFinder<AdUnit>) adUnitFinder;
	}

	public AdUnitFinder<com.google.api.ads.dfp.axis.v201405.AdUnit> getAdUnitFinderV201405() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession, DfpVersion.V_201405);
		}
		return (AdUnitFinder<com.google.api.ads.dfp.axis.v201405.AdUnit>) adUnitFinder;
	}

	public AdUnitFinder<com.google.api.ads.dfp.axis.v201408.AdUnit> getAdUnitFinderV201408() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession, DfpVersion.V_201408);
		}
		return (AdUnitFinder<com.google.api.ads.dfp.axis.v201408.AdUnit>) adUnitFinder;
	}
}
```
This will be invoked as
``` java
DfpFinderFactory dfpFinderFactory = new DfpFinderFactory(dfpServices, dfpSession);
		AdUnitFinder<com.google.api.ads.dfp.axis.v201408.AdUnit> adUnitFinder = dfpFinderFactory.getAdUnitFinderV201408();
		com.google.api.ads.dfp.axis.v201408.AdUnit adUnit = adUnitFinder.findRoot();
```

As given above the getAdUnitFinderV201408() will return a strongly typed object but the user has to make sure to call the correct method.

**Solution 2**
``` java
public class DfpFinderFactory {

	private AdUnitFinder<?> adUnitFinder;
	private OrderFinder<?> orderFinder;
	private DfpServices dfpServices;
	private DfpSession dfpSession;
	private DfpVersion dfpVersion;

	public DfpFinderFactory(DfpVersion version, DfpServices dfpServices, DfpSession dfpSession) {
		super();
		this.dfpServices = dfpServices;
		this.dfpSession = dfpSession;
		this.dfpVersion = version;
	}
public <T> AdUnitFinder<T> getAdUnitFinder() {
		if (adUnitFinder == null) {
			adUnitFinder = new AdUnitFinder<T>(dfpServices, dfpSession, dfpVersion);
		}
		return (AdUnitFinder<T>) adUnitFinder;
	}
}
```
This will be invoked as
``` java
	DfpFinderFactory dfpFinderFactory = new DfpFinderFactory(DfpVersion.V_201403, dfpServices, dfpSession);
		AdUnitFinder<AdUnit> adUnitFinder=dfpFinderFactory.getAdUnitFinder();
		.AdUnit adUnit = adUnitFinder.findRoot();
```
As given above the getAdUnitFinder() will return a ``` AdUnitFinder<Object>``` and the user can set anything for the generic type <AdUnit>. But if a wrong type is set then a Runtime exception will be thrown.

**Solution 3**
Have different Finder Factories for each version.
``` java
public class DfpV201408FinderFactory {

	private AdUnitFinder<?> adUnitFinder;
	private OrderFinder<?> orderFinder;
	private DfpServices dfpServices;
	private DfpSession dfpSession;

	public DfpV201408FinderFactory (DfpServices dfpServices, DfpSession dfpSession) {
			super();
			this.dfpServices = dfpServices;
			this.dfpSession = dfpSession;
		}
		
	public AdUnitFinder<AdUnit> getAdUnitFinder() {
		 if (adUnitFinder == null) {
		         adUnitFinder = new AdUnitFinder<AdUnit>(dfpServices, dfpSession,
			 DfpVersion.V_201403);
	         }
		 return (AdUnitFinder<AdUnit>) adUnitFinder;
        }
		 
	public OrderFinder<Order> getOrderFinder() {
		 if (adUnitFinder == null) {
			 orderFinder = new OrderFinder(dfpServices, dfpSession,DfpVersion.V_201403);
		 }
		 return (OrderFinder<Order>) orderFinder;
	}
}
```
This will be invoked as
``` java
	DfpV201408FinderFactory factory=new DfpV201408FinderFactory(dfpServices, dfpSession);
	AdUnitFinder<AdUnit> finder=factory.getAdUnitFinder();
	finder.findRoot();
```
As given above this solution is strongly typed but we need to have a factory class for each version.

Out of the above solutions I prefer Solution 3. Let me know your ideas on this. Will further see if there is a better way to solve this.

cc @gunith 

Piumika

**Comment by tonivdv** [comment]
@piumika And if you do solution 3 but without putting the version in the name, you make separate packages for it? Would be a bit cleaner don't you think?

**Comment by piumika** [comment]
Yes @tonivdv , that would be cleaner and better. Having the version number in the class name is ugly.

**Comment by tonivdv** [comment]
Let's try that :)

**Comment by piumika** [comment]
Hi @tonivdv ,

I committed the changes with the factory.

In the adserver-api I see that the finders have been used by passing the services in the constructors.
``` java
	final AdUnitFinder<AdUnit> adUnitFinder = new AdUnitFinder(serviceFactory.getInventoryService(), serviceFactory.getNetworkService();			
```
Do we still have to support constructors that accept the services? Can we use the dfp util as given below from the adserver api? (Without passing separate services we will be passing only the DfpServices and DfpSession)

``` java
DfpFinderFactory factory=new DfpFinderFactory(dfpServices, dfpSession);
AdUnitFinder<AdUnit> finder=factory.getAdUnitFinder();
finder.findRoot();
```

**Comment by tonivdv** [comment]
I did that because otherwise it does oblige the dev to always pass dfpService and dfpSession everywhere in the application where the Finder needs to be used ...

So maybe but not sure. Need to look into this deeper.

**Comment by piumika** [comment]
I feel that if we are going for  a DfpFinderFactory its better to pass the dfpService and the dfpSession to this factory without passing the individual services.The DfpFinderFactory should be initialized once and the factory should be used to get the finders. @tonivdv and @gunith  what do you think of this solution?
``` java
DfpFinderFactory factory=new DfpFinderFactory(dfpServices, dfpSession);
AdUnitFinder<AdUnit> finder=factory.getAdUnitFinder();
finder.findRoot();
```
At the moment in the dfp-adserver-api the dfpsession and dfpservices are not exposed in the DoubleClickAdService and only the individual services are exposed. So if we are going for this solution we might have to change the DoubleClickAdService (in dfp-adserver-api)  to expose the dfpsession and the dfpservices as well.Let me know your ideas on this.

**Comment by gunith** [comment]
I think involving services as @piumika suggests is a good idea. I feel that using of the services makes the code more complex and long as AdUnitFinder is required to act on services belonging to many versions. Also, I see its not needed as I see dfpsession and dfpservices as equivalent parameters to the services.

**Comment by tonivdv** [comment]
@piumika @gunith fine for me

**Comment by tonivdv** [comment]
If you could squash your commits again :)

**Comment by piumika** [comment]
Hello @tonivdv , @gunith ,
The last two commits were related to merging adlogix/master to the fork. If I use the following command to squash the last 3 commits do you think it can cause any issues when merging the PR to adlogix/master?

git reset --soft HEAD~3 &&
git commit

**Comment by tonivdv** [comment]
Did you try as in http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by piumika** [comment]
Hello @tonivdv 
I followed the instructions in the link you gave. It was a bit different as the feature is in a fork and not a branch. Following are the steps that I followed, but I was not able to squash the commits. Could it be because there is a merge from master in the middle ? Am I doing something wrong?

>git clone https://github.com/piumika/googleads-dfp-utils.git
>git remote add -f adlogix https://github.com/adlogix/googleads-dfp-utils.git
>git log --oneline adlogix/master...origin/master ->showed 3 commits correctly
>git rebase -i adlogix/master -> showed two commits (799e230b226c097baa2e926614c4f72b4806bc00 and 1558cbcbd342836b50e6b721e90fd4837c2ced76) did not show the merge from master
followed the steps in the link to change the pick to squash in the editor and saved the commit message correctly.But still the log shows 3 commits as before
>git log --oneline adlogix/master...origin/master-->still shows 3 commits

**Pull request merged**
